# Generated by Django 5.1.3 on 2024-12-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Num_ficha',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
